SET LINESIZE 250
SET PAGESIZE 200
COL PROGRAM FOR A40
COL MODULE FOR A50
COL EVENT FOR A50
COL STATE FOR A20

SELECT PROGRAM, MODULE, EVENT, STATE FROM V$SESSION
WHERE
STATUS = 'ACTIVE'
AND TYPE <> 'BACKGROUND'
ORDER BY 1
/
